"use client";

import { useEditor, EditorContent } from '@tiptap/react';
import StarterKit from '@tiptap/starter-kit';
import { Underline } from '@tiptap/extension-underline';
import { Table } from '@tiptap/extension-table';
import { TableRow } from '@tiptap/extension-table-row';
import { TableCell } from '@tiptap/extension-table-cell';
import { TableHeader } from '@tiptap/extension-table-header';
import { Bold, Italic, Underline as UnderlineIcon } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { cn } from '@/lib/utils';
import { useEffect } from 'react';

interface RichTextEditorProps {
  value: string;
  onChange: (value: string) => void;
  placeholder?: string;
  className?: string;
}

export function RichTextEditor({ value, onChange, placeholder, className }: RichTextEditorProps) {
  // Helper to preserve line breaks for legacy plain-text posts
  const formatInitialContent = (content: string) => {
    if (!content) return '';
    // If it looks like HTML generated by tiptap, return as is
    if (content.includes('<p>') || content.includes('<br>') || content.includes('<table>')) {
      return content;
    }
    // Otherwise convert \n to <br> so Tiptap parses the newlines correctly
    return content.replace(/\n/g, '<br>');
  };

  const editor = useEditor({
    extensions: [
      StarterKit.configure({
        heading: false,
      }),
      Underline,
      Table.configure({
        resizable: true,
      }),
      TableRow,
      TableHeader,
      TableCell,
    ],
    content: formatInitialContent(value),
    editorProps: {
      attributes: {
        class: cn(
          'prose prose-sm dark:prose-invert max-w-none focus:outline-none min-h-[120px] px-0 leading-relaxed text-[15px] tiptap-editor whitespace-pre-wrap',
          className
        ),
      },
    },
    onUpdate: ({ editor }) => {
      // If content is empty or just an empty paragraph, send empty string to trigger validation correctly
      const html = editor.getHTML();
      const isEmpty = editor.getText().trim() === '';
      // We still want to allow tables, images, etc. even if text is empty. 
      // But for simple validation, checking length is tricky. Let's just pass html.
      onChange(html);
    },
  });

  // Update content if value changes from outside (e.g. form reset or initialData load)
  useEffect(() => {
    if (editor && value) {
      const formatted = formatInitialContent(value);
      // Only set content if the current editor HTML is completely different to avoid cursor jumps
      if (editor.getHTML() !== formatted && editor.getHTML() !== value) {
        editor.commands.setContent(formatted);
      }
    } else if (editor && !value) {
      editor.commands.clearContent();
    }
  }, [value, editor]);

  if (!editor) {
    return null;
  }

  return (
    <div className="flex flex-col gap-2 w-full">
      <div className="flex items-center gap-1 border-b border-border/40 pb-2 mb-2">
        <Button
          type="button"
          variant="ghost"
          size="icon"
          onClick={() => editor.chain().focus().toggleBold().run()}
          className={cn("h-8 w-8 rounded-md hover:bg-secondary/80", editor.isActive('bold') && "bg-secondary text-foreground")}
        >
          <Bold className="h-4 w-4" />
        </Button>
        <Button
          type="button"
          variant="ghost"
          size="icon"
          onClick={() => editor.chain().focus().toggleItalic().run()}
          className={cn("h-8 w-8 rounded-md hover:bg-secondary/80", editor.isActive('italic') && "bg-secondary text-foreground")}
        >
          <Italic className="h-4 w-4" />
        </Button>
        <Button
          type="button"
          variant="ghost"
          size="icon"
          onClick={() => editor.chain().focus().toggleUnderline().run()}
          className={cn("h-8 w-8 rounded-md hover:bg-secondary/80", editor.isActive('underline') && "bg-secondary text-foreground")}
        >
          <UnderlineIcon className="h-4 w-4" />
        </Button>
        {/* <div className="w-px h-4 bg-border/60 mx-1" />
        <Button
          type="button"
          variant="ghost"
          size="icon"
          onClick={() => editor.chain().focus().insertTable({ rows: 3, cols: 3, withHeaderRow: true }).run()}
          className="h-8 w-8 rounded-md hover:bg-secondary/80"
          title="Insert Table"
        >
          <TableIcon className="h-4 w-4" />
        </Button> */}
      </div>
      <EditorContent editor={editor} className="w-full bg-transparent tiptap-container" />
    </div>
  );
}
